[package]
name = "mount"
version = "0.1.0"
authors = ["Zach <zach_41@163.com>"]

[dependencies]
webdemo = { path = "../../../webdemo" }
sequence_trie = "0.3"
log = "*"

[dev-dependencies]
env_logger = "0.4.1"
